server:
  port: 8080
spring:
  devtools:
    livereload:
      port: 35730
  profiles:
    active: prod
  mail:
    host: smtp.163.com
    username: qidian_webcrawler@163.com
    password: YMTEGGNPIRROGPQS
